export interface Country {
  code: string;
  name: string;
  prefix: string;
}

// Complete list of countries with Ecuador (+593) first, followed by others alphabetically in Spanish
export const COUNTRIES: Country[] = [
  { code: "ec", name: "Ecuador", prefix: "+593" },
  { code: "af", name: "Afganistán", prefix: "+93" },
  { code: "al", name: "Albania", prefix: "+355" },
  { code: "de", name: "Alemania", prefix: "+49" },
  { code: "ad", name: "Andorra", prefix: "+376" },
  { code: "ao", name: "Angola", prefix: "+244" },
  { code: "ag", name: "Antigua y Barbuda", prefix: "+1" },
  { code: "sa", name: "Arabia Saudita", prefix: "+966" },
  { code: "dz", name: "Argelia", prefix: "+213" },
  { code: "ar", name: "Argentina", prefix: "+54" },
  { code: "am", name: "Armenia", prefix: "+374" },
  { code: "au", name: "Australia", prefix: "+61" },
  { code: "at", name: "Austria", prefix: "+43" },
  { code: "az", name: "Azerbaiyán", prefix: "+994" },
  { code: "bs", name: "Bahamas", prefix: "+1" },
  { code: "bd", name: "Bangladés", prefix: "+880" },
  { code: "bb", name: "Barbados", prefix: "+1" },
  { code: "be", name: "Bélgica", prefix: "+32" },
  { code: "bz", name: "Belice", prefix: "+501" },
  { code: "bj", name: "Benín", prefix: "+229" },
  { code: "bo", name: "Bolivia", prefix: "+591" },
  { code: "ba", name: "Bosnia y Herzegovina", prefix: "+387" },
  { code: "bw", name: "Botsuana", prefix: "+267" },
  { code: "br", name: "Brasil", prefix: "+55" },
  { code: "bn", name: "Brunéi", prefix: "+673" },
  { code: "bg", name: "Bulgaria", prefix: "+359" },
  { code: "bf", name: "Burkina Faso", prefix: "+226" },
  { code: "bi", name: "Burundi", prefix: "+257" },
  { code: "bt", name: "Bután", prefix: "+975" },
  { code: "cv", name: "Cabo Verde", prefix: "+238" },
  { code: "kh", name: "Camboya", prefix: "+855" },
  { code: "cm", name: "Camerún", prefix: "+237" },
  { code: "ca", name: "Canadá", prefix: "+1" },
  { code: "qa", name: "Catar", prefix: "+974" },
  { code: "td", name: "Chad", prefix: "+235" },
  { code: "cl", name: "Chile", prefix: "+56" },
  { code: "cn", name: "China", prefix: "+86" },
  { code: "cy", name: "Chipre", prefix: "+357" },
  { code: "co", name: "Colombia", prefix: "+57" },
  { code: "km", name: "Comoras", prefix: "+269" },
  { code: "kp", name: "Corea del Norte", prefix: "+850" },
  { code: "kr", name: "Corea del Sur", prefix: "+82" },
  { code: "ci", name: "Costa de Marfil", prefix: "+225" },
  { code: "cr", name: "Costa Rica", prefix: "+506" },
  { code: "hr", name: "Croacia", prefix: "+385" },
  { code: "cu", name: "Cuba", prefix: "+53" },
  { code: "dk", name: "Dinamarca", prefix: "+45" },
  { code: "dm", name: "Dominica", prefix: "+1" },
  { code: "eg", name: "Egipto", prefix: "+20" },
  { code: "sv", name: "El Salvador", prefix: "+503" },
  { code: "ae", name: "Emiratos Árabes Unidos", prefix: "+971" },
  { code: "er", name: "Eritrea", prefix: "+291" },
  { code: "sk", name: "Eslovaquia", prefix: "+421" },
  { code: "si", name: "Eslovenia", prefix: "+386" },
  { code: "es", name: "España", prefix: "+34" },
  { code: "us", name: "Estados Unidos", prefix: "+1" },
  { code: "ee", name: "Estonia", prefix: "+372" },
  { code: "et", name: "Etiopía", prefix: "+251" },
  { code: "ph", name: "Filipinas", prefix: "+63" },
  { code: "fi", name: "Finlandia", prefix: "+358" },
  { code: "fj", name: "Fiyi", prefix: "+679" },
  { code: "fr", name: "Francia", prefix: "+33" },
  { code: "ga", name: "Gabón", prefix: "+241" },
  { code: "gm", name: "Gambia", prefix: "+220" },
  { code: "ge", name: "Georgia", prefix: "+995" },
  { code: "gh", name: "Ghana", prefix: "+233" },
  { code: "gi", name: "Gibraltar", prefix: "+350" },
  { code: "gd", name: "Granada", prefix: "+1" },
  { code: "gr", name: "Grecia", prefix: "+30" },
  { code: "gl", name: "Groenlandia", prefix: "+299" },
  { code: "gt", name: "Guatemala", prefix: "+502" },
  { code: "gn", name: "Guinea", prefix: "+224" },
  { code: "gq", name: "Guinea Ecuatorial", prefix: "+240" },
  { code: "gw", name: "Guinea-Bisáu", prefix: "+245" },
  { code: "gy", name: "Guyana", prefix: "+592" },
  { code: "ht", name: "Haití", prefix: "+509" },
  { code: "hn", name: "Honduras", prefix: "+504" },
  { code: "hk", name: "Hong Kong", prefix: "+852" },
  { code: "hu", name: "Hungría", prefix: "+36" },
  { code: "in", name: "India", prefix: "+91" },
  { code: "id", name: "Indonesia", prefix: "+62" },
  { code: "iq", name: "Irak", prefix: "+964" },
  { code: "ir", name: "Irán", prefix: "+98" },
  { code: "ie", name: "Irlanda", prefix: "+353" },
  { code: "is", name: "Islandia", prefix: "+354" },
  { code: "il", name: "Israel", prefix: "+972" },
  { code: "it", name: "Italia", prefix: "+39" },
  { code: "jm", name: "Jamaica", prefix: "+1" },
  { code: "jp", name: "Japón", prefix: "+81" },
  { code: "jo", name: "Jordania", prefix: "+962" },
  { code: "kz", name: "Kazajistán", prefix: "+7" },
  { code: "ke", name: "Kenia", prefix: "+254" },
  { code: "kg", name: "Kirguistán", prefix: "+996" },
  { code: "ki", name: "Kiribati", prefix: "+686" },
  { code: "kw", name: "Kuwait", prefix: "+965" },
  { code: "la", name: "Laos", prefix: "+856" },
  { code: "ls", name: "Lesoto", prefix: "+266" },
  { code: "lv", name: "Letonia", prefix: "+371" },
  { code: "lb", name: "Líbano", prefix: "+961" },
  { code: "lr", name: "Liberia", prefix: "+231" },
  { code: "ly", name: "Libia", prefix: "+218" },
  { code: "li", name: "Liechtenstein", prefix: "+423" },
  { code: "lt", name: "Lituania", prefix: "+370" },
  { code: "lu", name: "Luxemburgo", prefix: "+352" },
  { code: "mo", name: "Macao", prefix: "+853" },
  { code: "mk", name: "Macedonia del Norte", prefix: "+389" },
  { code: "mg", name: "Madagascar", prefix: "+261" },
  { code: "my", name: "Malasia", prefix: "+60" },
  { code: "mw", name: "Malaui", prefix: "+265" },
  { code: "mv", name: "Maldivas", prefix: "+960" },
  { code: "ml", name: "Malí", prefix: "+223" },
  { code: "mt", name: "Malta", prefix: "+356" },
  { code: "ma", name: "Marruecos", prefix: "+212" },
  { code: "mu", name: "Mauricio", prefix: "+230" },
  { code: "mr", name: "Mauritania", prefix: "+222" },
  { code: "mx", name: "México", prefix: "+52" },
  { code: "fm", name: "Micronesia", prefix: "+691" },
  { code: "md", name: "Moldavia", prefix: "+373" },
  { code: "mc", name: "Mónaco", prefix: "+377" },
  { code: "mn", name: "Mongolia", prefix: "+976" },
  { code: "me", name: "Montenegro", prefix: "+382" },
  { code: "mz", name: "Mozambique", prefix: "+258" },
  { code: "na", name: "Namibia", prefix: "+264" },
  { code: "nr", name: "Nauru", prefix: "+674" },
  { code: "np", name: "Nepal", prefix: "+977" },
  { code: "ni", name: "Nicaragua", prefix: "+505" },
  { code: "ne", name: "Níger", prefix: "+227" },
  { code: "ng", name: "Nigeria", prefix: "+234" },
  { code: "no", name: "Noruega", prefix: "+47" },
  { code: "nz", name: "Nueva Zelanda", prefix: "+64" },
  { code: "om", name: "Omán", prefix: "+968" },
  { code: "nl", name: "Países Bajos", prefix: "+31" },
  { code: "pk", name: "Pakistán", prefix: "+92" },
  { code: "pw", name: "Palaos", prefix: "+680" },
  { code: "ps", name: "Palestina", prefix: "+970" },
  { code: "pa", name: "Panamá", prefix: "+507" },
  { code: "pg", name: "Papúa Nueva Guinea", prefix: "+675" },
  { code: "py", name: "Paraguay", prefix: "+595" },
  { code: "pe", name: "Perú", prefix: "+51" },
  { code: "pf", name: "Polinesia Francesa", prefix: "+689" },
  { code: "pl", name: "Polonia", prefix: "+48" },
  { code: "pt", name: "Portugal", prefix: "+351" },
  { code: "pr", name: "Puerto Rico", prefix: "+1" },
  { code: "gb", name: "Reino Unido", prefix: "+44" },
  { code: "cf", name: "República Centroafricana", prefix: "+236" },
  { code: "cz", name: "República Checa", prefix: "+420" },
  { code: "do", name: "República Dominicana", prefix: "+1" },
  { code: "rw", name: "Ruanda", prefix: "+250" },
  { code: "ro", name: "Rumania", prefix: "+40" },
  { code: "ru", name: "Rusia", prefix: "+7" },
  { code: "ws", name: "Samoa", prefix: "+685" },
  { code: "kn", name: "San Cristóbal y Nieves", prefix: "+1" },
  { code: "sm", name: "San Marino", prefix: "+378" },
  { code: "vc", name: "San Vicente y las Granadinas", prefix: "+1" },
  { code: "lc", name: "Santa Lucía", prefix: "+1" },
  { code: "st", name: "Santo Tomé y Príncipe", prefix: "+239" },
  { code: "sn", name: "Senegal", prefix: "+221" },
  { code: "rs", name: "Serbia", prefix: "+381" },
  { code: "sc", name: "Seychelles", prefix: "+248" },
  { code: "sl", name: "Sierra Leona", prefix: "+232" },
  { code: "sg", name: "Singapur", prefix: "+65" },
  { code: "sy", name: "Siria", prefix: "+963" },
  { code: "so", name: "Somalia", prefix: "+252" },
  { code: "lk", name: "Sri Lanka", prefix: "+94" },
  { code: "za", name: "Sudáfrica", prefix: "+27" },
  { code: "sd", name: "Sudán", prefix: "+249" },
  { code: "se", name: "Suecia", prefix: "+46" },
  { code: "ch", name: "Suiza", prefix: "+41" },
  { code: "sr", name: "Surinam", prefix: "+597" },
  { code: "th", name: "Tailandia", prefix: "+66" },
  { code: "tw", name: "Taiwán", prefix: "+886" },
  { code: "tz", name: "Tanzania", prefix: "+255" },
  { code: "tj", name: "Tayikistán", prefix: "+992" },
  { code: "tg", name: "Togo", prefix: "+228" },
  { code: "to", name: "Tonga", prefix: "+676" },
  { code: "tt", name: "Trinidad y Tobago", prefix: "+1" },
  { code: "tn", name: "Túnez", prefix: "+216" },
  { code: "tm", name: "Turkmenistán", prefix: "+993" },
  { code: "tr", name: "Turquía", prefix: "+90" },
  { code: "tv", name: "Tuvalu", prefix: "+688" },
  { code: "ua", name: "Ucrania", prefix: "+380" },
  { code: "ug", name: "Uganda", prefix: "+256" },
  { code: "uy", name: "Uruguay", prefix: "+598" },
  { code: "uz", name: "Uzbekistán", prefix: "+998" },
  { code: "vu", name: "Vanuatu", prefix: "+678" },
  { code: "ve", name: "Venezuela", prefix: "+58" },
  { code: "vn", name: "Vietnam", prefix: "+84" },
  { code: "ye", name: "Yemen", prefix: "+967" },
  { code: "dj", name: "Yibuti", prefix: "+253" },
  { code: "zm", name: "Zambia", prefix: "+260" },
  { code: "zw", name: "Zimbabue", prefix: "+263" }
];

export const COUNTRY_PREFIXES: Record<string, string> = COUNTRIES.reduce((acc, c) => {
  acc[c.code] = c.prefix;
  return acc;
}, {} as Record<string, string>);
